// CREATE TABLE listings (
//     id INT PRIMARY KEY AUTO_INCREMENT,
//     host_id INT NOT NULL,
//     title VARCHAR(255) NOT NULL,
//     description TEXT,
//     property_type VARCHAR(50) NOT NULL,
//     room_type VARCHAR(50) NOT NULL,
//     address VARCHAR(255) NOT NULL,
//     city VARCHAR(100) NOT NULL,
//     state VARCHAR(100),
//     country VARCHAR(100) NOT NULL,
//     price_per_night DECIMAL(10, 2) NOT NULL,
//     number_of_bedrooms INT NOT NULL,
//     number_of_bathrooms INT NOT NULL,
//     max_guests INT NOT NULL,
//     category VARCHAR(50),
//     all_rooms_have_locks BOOLEAN DEFAULT FALSE,
//     amenities JSON,
//     who_else_might_be_there TEXT,
//     cover_photo VARCHAR(255),
//     additional_photos JSON,
//     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
//     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
// );